const guideUi = {
  en:{language:'Language',planner:'Open the free meeting planner',more:'More useful guides',home:'Meeting planner',privacy:'Privacy',footer:'A free world meeting time finder.'},
  es:{language:'Idioma',planner:'Abrir el planificador gratuito',more:'Más guías útiles',home:'Planificador de reuniones',privacy:'Privacidad',footer:'Un buscador gratuito de horarios mundiales.'},
  fr:{language:'Langue',planner:'Ouvrir le planificateur gratuit',more:'Autres guides utiles',home:'Planificateur de réunion',privacy:'Confidentialité',footer:'Un outil gratuit de recherche d’horaires mondiaux.'},
  de:{language:'Sprache',planner:'Kostenlosen Meetingplaner öffnen',more:'Weitere hilfreiche Leitfäden',home:'Meetingplaner',privacy:'Datenschutz',footer:'Ein kostenloser weltweiter Meetingzeit-Finder.'},
  pt:{language:'Idioma',planner:'Abrir o planejador gratuito',more:'Mais guias úteis',home:'Planejador de reuniões',privacy:'Privacidade',footer:'Um localizador gratuito de horários mundiais.'}
};

const guides = {
  converter:{
    en:{title:'Meeting Time-Zone Converter | Common Hours',description:'Convert meeting times across cities and time zones while comparing working hours, dates, weekends and holidays.',eyebrow:'Time-zone conversion',heading:'Convert a meeting time for everyone',intro:'A useful meeting time-zone converter does more than add or subtract hours. It should use the meeting date, each city’s local rules and the length of the meeting.',sections:[['Why the date matters','Time-zone differences are not fixed throughout the year. Countries change clocks on different dates, and many never change them. Always convert the actual meeting date rather than relying on a familiar offset.'],['How to convert a proposed meeting',['Add every participant’s city, not only a UTC offset.','Choose the intended meeting date and duration.','Compare the local start and end times for everyone.','Move the selected time in 30-minute steps until the trade-off feels reasonable.']]],note:'Common Hours uses named city time zones for the selected date, helping account for applicable daylight-saving changes automatically.'},
    es:{title:'Conversor de zonas horarias para reuniones | Common Hours',description:'Convierte horas de reunión entre ciudades y compara horarios laborales, fechas, fines de semana y festivos.',eyebrow:'Conversión de zonas horarias',heading:'Convierte una hora de reunión para todos',intro:'Un buen conversor hace más que sumar o restar horas. Debe considerar la fecha, las reglas locales de cada ciudad y la duración.',sections:[['Por qué importa la fecha','Las diferencias horarias no son fijas todo el año. Los países cambian el reloj en fechas distintas y muchos nunca lo cambian. Convierte siempre la fecha real de la reunión.'],['Cómo convertir una propuesta',['Añade la ciudad de cada participante, no solo un desfase UTC.','Elige la fecha y duración previstas.','Compara las horas locales de inicio y fin.','Mueve la hora en intervalos de 30 minutos hasta encontrar un equilibrio razonable.']]],note:'Common Hours usa zonas horarias de ciudades para la fecha elegida y contempla automáticamente los cambios de horario aplicables.'},
    fr:{title:'Convertisseur de fuseaux horaires pour réunions | Common Hours',description:'Convertissez les heures de réunion entre villes et comparez horaires de travail, dates, week-ends et jours fériés.',eyebrow:'Conversion de fuseaux horaires',heading:'Convertissez une heure de réunion pour tous',intro:'Un bon convertisseur ne se contente pas d’ajouter ou soustraire des heures. Il tient compte de la date, des règles locales et de la durée.',sections:[['Pourquoi la date compte','Les écarts horaires ne restent pas fixes toute l’année. Les pays changent d’heure à des dates différentes et beaucoup ne changent jamais. Convertissez toujours la date réelle.'],['Comment convertir une proposition',['Ajoutez la ville de chaque participant, pas seulement un décalage UTC.','Choisissez la date et la durée prévues.','Comparez les heures locales de début et de fin.','Déplacez l’heure par pas de 30 minutes jusqu’à obtenir un compromis raisonnable.']]],note:'Common Hours utilise les fuseaux des villes à la date choisie afin de tenir automatiquement compte des changements d’heure applicables.'},
    de:{title:'Zeitzonen-Umrechner für Meetings | Common Hours',description:'Rechne Meetingzeiten zwischen Städten um und vergleiche Arbeitszeiten, Daten, Wochenenden und Feiertage.',eyebrow:'Zeitzonenumrechnung',heading:'Rechne eine Meetingzeit für alle um',intro:'Ein guter Zeitzonen-Umrechner addiert oder subtrahiert nicht nur Stunden. Er berücksichtigt Datum, lokale Regeln und Meetingdauer.',sections:[['Warum das Datum wichtig ist','Zeitunterschiede bleiben nicht das ganze Jahr gleich. Länder stellen ihre Uhren an unterschiedlichen Tagen um, viele gar nicht. Rechne deshalb immer das tatsächliche Meetingdatum um.'],['So rechnest du einen Vorschlag um',['Füge die Stadt jeder Person hinzu, nicht nur einen UTC-Versatz.','Wähle Datum und Dauer des Meetings.','Vergleiche lokale Start- und Endzeiten.','Verschiebe die Zeit in 30-Minuten-Schritten, bis der Kompromiss passt.']]],note:'Common Hours verwendet benannte Stadtzeitzonen für das gewählte Datum und berücksichtigt damit geltende Zeitumstellungen automatisch.'},
    pt:{title:'Conversor de fusos horários para reuniões | Common Hours',description:'Converta horários entre cidades e compare expediente, datas, fins de semana e feriados.',eyebrow:'Conversão de fusos horários',heading:'Converta um horário de reunião para todos',intro:'Um bom conversor faz mais do que somar ou subtrair horas. Ele considera a data, as regras locais de cada cidade e a duração.',sections:[['Por que a data importa','As diferenças de horário não são fixas durante o ano. Países mudam os relógios em datas diferentes e muitos nunca mudam. Converta sempre a data real da reunião.'],['Como converter uma proposta',['Adicione a cidade de cada participante, não apenas um deslocamento UTC.','Escolha a data e a duração previstas.','Compare os horários locais de início e término.','Mova o horário em passos de 30 minutos até chegar a um equilíbrio razoável.']]],note:'O Common Hours usa fusos de cidades para a data escolhida, considerando automaticamente as mudanças de horário aplicáveis.'}
  },
  planner:{
    en:{title:'International Meeting Planner Guide | Common Hours',description:'Plan fair international meetings across countries with a practical checklist for time zones, working hours and meeting duration.',eyebrow:'International scheduling',heading:'Plan a fair international meeting',intro:'The best international meeting time is not always perfect for everyone. A clear process helps you find the least disruptive option and share the inconvenience fairly.',sections:[['A practical planning checklist',['List every participant’s city and confirm the meeting date.','Set the real duration before comparing availability.','Prefer overlap within normal weekday working hours.','Check local weekends and public-holiday notices.','If no good overlap exists, rotate early or late meetings over time.']],['Make the invitation unambiguous','Write the date, local time and time zone in the invitation. A calendar invitation is helpful, but a readable summary lets participants catch mistakes before the meeting.']],note:'For recurring global meetings, fairness often matters more than choosing the same clock time every week.'},
    es:{title:'Guía para planificar reuniones internacionales | Common Hours',description:'Planifica reuniones internacionales justas con una lista práctica sobre zonas horarias, horarios laborales y duración.',eyebrow:'Planificación internacional',heading:'Planifica una reunión internacional justa',intro:'La mejor hora internacional no siempre es perfecta para todos. Un proceso claro ayuda a encontrar la opción menos incómoda y repartir el esfuerzo.',sections:[['Lista práctica',['Anota la ciudad de cada participante y confirma la fecha.','Define la duración real antes de comparar disponibilidad.','Prefiere coincidencias dentro del horario laboral normal.','Comprueba fines de semana y avisos de festivos.','Si no hay una buena coincidencia, alterna las reuniones tempranas o tardías.']],['Haz que la invitación sea inequívoca','Escribe la fecha, hora local y zona horaria en la invitación. El calendario ayuda, pero un resumen legible permite detectar errores.']],note:'En reuniones globales periódicas, la equidad suele importar más que mantener siempre la misma hora de reloj.'},
    fr:{title:'Guide de planification de réunion internationale | Common Hours',description:'Planifiez des réunions internationales équitables grâce à une liste pratique sur les fuseaux, horaires et durées.',eyebrow:'Planification internationale',heading:'Planifiez une réunion internationale équitable',intro:'La meilleure heure n’est pas toujours parfaite pour tous. Une méthode claire aide à trouver l’option la moins gênante et à partager l’effort.',sections:[['Liste pratique',['Indiquez la ville de chaque participant et confirmez la date.','Fixez la durée réelle avant de comparer les disponibilités.','Privilégiez les heures de travail normales en semaine.','Vérifiez les week-ends et avis de jours fériés.','Sans bon chevauchement, alternez les réunions tôt ou tard.']],['Rendez l’invitation sans ambiguïté','Écrivez la date, l’heure locale et le fuseau dans l’invitation. Le calendrier aide, mais un résumé lisible permet de repérer les erreurs.']],note:'Pour les réunions mondiales récurrentes, l’équité compte souvent davantage que le maintien de la même heure chaque semaine.'},
    de:{title:'Leitfaden für internationale Meetings | Common Hours',description:'Plane faire internationale Meetings mit einer praktischen Checkliste zu Zeitzonen, Arbeitszeiten und Dauer.',eyebrow:'Internationale Planung',heading:'Plane ein faires internationales Meeting',intro:'Die beste internationale Meetingzeit ist nicht immer für alle perfekt. Ein klarer Ablauf hilft, die geringste Belastung zu finden und fair zu verteilen.',sections:[['Praktische Checkliste',['Notiere die Stadt aller Teilnehmenden und bestätige das Datum.','Lege die echte Dauer vor dem Vergleich fest.','Bevorzuge Überschneidungen innerhalb normaler Arbeitszeiten.','Prüfe lokale Wochenenden und Feiertagshinweise.','Wenn es keine gute Überschneidung gibt, wechsle frühe und späte Termine ab.']],['Formuliere die Einladung eindeutig','Nenne Datum, Ortszeit und Zeitzone. Eine Kalendereinladung hilft, aber eine lesbare Zusammenfassung macht Fehler sichtbar.']],note:'Bei wiederkehrenden globalen Meetings ist Fairness oft wichtiger als jede Woche dieselbe Uhrzeit.'},
    pt:{title:'Guia para planejar reuniões internacionais | Common Hours',description:'Planeje reuniões internacionais justas com uma lista prática de fusos, expedientes e duração.',eyebrow:'Agendamento internacional',heading:'Planeje uma reunião internacional justa',intro:'O melhor horário internacional nem sempre é perfeito para todos. Um processo claro ajuda a encontrar a opção menos inconveniente e dividir o esforço.',sections:[['Lista prática',['Registre a cidade de cada participante e confirme a data.','Defina a duração real antes de comparar disponibilidade.','Prefira sobreposição dentro do expediente normal.','Confira fins de semana e avisos de feriados locais.','Sem boa sobreposição, alterne reuniões cedo ou tarde.']],['Deixe o convite inequívoco','Informe a data, o horário local e o fuso no convite. O calendário ajuda, mas um resumo legível permite detectar erros.']],note:'Para reuniões globais recorrentes, a justiça costuma ser mais importante do que manter sempre o mesmo horário.'}
  },
  dst:{
    en:{title:'Daylight Saving Time and Holiday Meeting Guide | Common Hours',description:'Avoid international scheduling errors caused by daylight-saving changes, date boundaries, weekends and public holidays.',eyebrow:'Dates and local calendars',heading:'Avoid daylight-saving and holiday surprises',intro:'International schedules can shift even when nobody changes the meeting. Clock changes, date boundaries and public holidays must be checked against the actual meeting date.',sections:[['Daylight-saving changes are not synchronized','Regions begin and end daylight saving time on different dates. For several weeks each year, a familiar city-to-city difference may be one hour larger or smaller than expected. Some places do not observe daylight saving time at all.'],['Check the local calendar',['Confirm the date shown in every participant’s city.','Look for weekend differences when meetings cross midnight.','Treat holiday notices as warnings rather than automatic exclusions.','Recheck recurring meetings near seasonal clock changes.']]],note:'Common Hours flags public holidays instead of hiding possible times, leaving the final decision with the people attending.'},
    es:{title:'Guía de horario de verano y festivos | Common Hours',description:'Evita errores causados por cambios de horario, límites de fecha, fines de semana y festivos.',eyebrow:'Fechas y calendarios locales',heading:'Evita sorpresas de horario de verano y festivos',intro:'Los horarios internacionales pueden cambiar aunque nadie mueva la reunión. Hay que comprobar los cambios de reloj, fechas y festivos para el día real.',sections:[['Los cambios no están sincronizados','Las regiones comienzan y terminan el horario de verano en fechas distintas. Durante varias semanas, la diferencia habitual entre ciudades puede variar una hora. Algunos lugares nunca cambian el reloj.'],['Comprueba el calendario local',['Confirma la fecha mostrada en cada ciudad.','Busca diferencias de fin de semana cuando se cruza la medianoche.','Trata los avisos de festivos como advertencias, no exclusiones automáticas.','Revisa las reuniones periódicas cerca de los cambios estacionales.']]],note:'Common Hours señala los festivos sin ocultar horas posibles, dejando la decisión final a los participantes.'},
    fr:{title:'Guide heure d’été et jours fériés | Common Hours',description:'Évitez les erreurs dues aux changements d’heure, changements de date, week-ends et jours fériés.',eyebrow:'Dates et calendriers locaux',heading:'Évitez les surprises liées aux changements d’heure et jours fériés',intro:'Les horaires internationaux peuvent changer sans déplacer la réunion. Vérifiez les changements d’heure, de date et les jours fériés pour la date réelle.',sections:[['Les changements ne sont pas synchronisés','Les régions commencent et terminent l’heure d’été à des dates différentes. Pendant plusieurs semaines, l’écart habituel entre deux villes peut varier d’une heure. Certains lieux ne changent jamais d’heure.'],['Vérifiez le calendrier local',['Confirmez la date affichée dans chaque ville.','Repérez les différences de week-end lors du passage à minuit.','Considérez les avis de jours fériés comme des avertissements.','Revérifiez les réunions récurrentes près des changements saisonniers.']]],note:'Common Hours signale les jours fériés sans masquer les heures possibles, laissant la décision finale aux participants.'},
    de:{title:'Leitfaden zu Sommerzeit und Feiertagen | Common Hours',description:'Vermeide internationale Planungsfehler durch Zeitumstellungen, Datumsgrenzen, Wochenenden und Feiertage.',eyebrow:'Daten und lokale Kalender',heading:'Vermeide Überraschungen durch Sommerzeit und Feiertage',intro:'Internationale Zeiten können sich ändern, obwohl niemand das Meeting verschiebt. Zeitumstellungen, Datumsgrenzen und Feiertage müssen für das echte Datum geprüft werden.',sections:[['Zeitumstellungen sind nicht synchron','Regionen beginnen und beenden die Sommerzeit an verschiedenen Tagen. Mehrere Wochen im Jahr kann der gewohnte Unterschied zwischen Städten um eine Stunde abweichen. Manche Orte stellen nie um.'],['Prüfe den lokalen Kalender',['Bestätige das Datum in jeder Stadt.','Achte beim Überschreiten von Mitternacht auf Wochenenden.','Behandle Feiertagshinweise als Warnungen, nicht als automatische Ausschlüsse.','Prüfe Serientermine rund um saisonale Zeitumstellungen erneut.']]],note:'Common Hours kennzeichnet Feiertage, ohne mögliche Zeiten auszublenden. Die endgültige Entscheidung bleibt bei den Teilnehmenden.'},
    pt:{title:'Guia de horário de verão e feriados | Common Hours',description:'Evite erros de agendamento causados por mudanças de horário, datas, fins de semana e feriados.',eyebrow:'Datas e calendários locais',heading:'Evite surpresas com horário de verão e feriados',intro:'Horários internacionais podem mudar mesmo sem alterar a reunião. Mudanças de relógio, viradas de data e feriados devem ser conferidos para a data real.',sections:[['As mudanças não são sincronizadas','Regiões iniciam e terminam o horário de verão em datas diferentes. Durante semanas, a diferença habitual entre cidades pode variar uma hora. Alguns lugares nunca mudam o relógio.'],['Confira o calendário local',['Confirme a data exibida em cada cidade.','Observe fins de semana quando a reunião cruza a meia-noite.','Trate avisos de feriado como alertas, não exclusões automáticas.','Revise reuniões recorrentes perto das mudanças sazonais.']]],note:'O Common Hours sinaliza feriados sem ocultar horários possíveis, deixando a decisão final para os participantes.'}
  }
};

const holidayGuidePositioning = {
  en:{title:'International Public Holiday Meeting Planner | Common Hours',description:'Check public holidays across countries before scheduling an international meeting.',eyebrow:'Public holidays across countries',heading:'Know when it’s a holiday there before you schedule',intro:'A time can fit everyone’s working hours and still be the wrong day. International meetings should be checked against each participant’s local public-holiday calendar.',note:'Common Hours flags public holidays for every selected location instead of silently removing the meeting time, so your team can make the final call.'},
  es:{title:'Planificador de reuniones y festivos internacionales | Common Hours',description:'Comprueba festivos entre países antes de programar una reunión internacional.',eyebrow:'Festivos entre países',heading:'Comprueba si allí es festivo antes de programar',intro:'Una hora puede encajar en todos los horarios laborales y aun así caer en el día equivocado. Comprueba el calendario festivo local de cada participante.',note:'Common Hours señala los festivos de cada ubicación sin eliminar silenciosamente la hora, para que el equipo tome la decisión final.'},
  fr:{title:'Planificateur de réunions et jours fériés internationaux | Common Hours',description:'Vérifiez les jours fériés de chaque pays avant de planifier une réunion internationale.',eyebrow:'Jours fériés selon les pays',heading:'Vérifiez si c’est un jour férié là-bas avant de planifier',intro:'Une heure peut convenir aux horaires de travail de tous tout en tombant le mauvais jour. Vérifiez le calendrier local de chaque participant.',note:'Common Hours signale les jours fériés de chaque lieu sans masquer l’heure proposée, afin que l’équipe prenne la décision finale.'},
  de:{title:'Internationaler Feiertags-Meetingplaner | Common Hours',description:'Prüfe Feiertage in verschiedenen Ländern, bevor du ein internationales Meeting planst.',eyebrow:'Feiertage in verschiedenen Ländern',heading:'Prüfe vor der Planung, ob dort Feiertag ist',intro:'Eine Uhrzeit kann in alle Arbeitszeiten passen und trotzdem auf den falschen Tag fallen. Prüfe den lokalen Feiertagskalender aller Teilnehmenden.',note:'Common Hours kennzeichnet Feiertage für jeden Ort, ohne die Meetingzeit auszublenden. So kann das Team selbst entscheiden.'},
  pt:{title:'Planejador de reuniões e feriados internacionais | Common Hours',description:'Confira feriados entre países antes de marcar uma reunião internacional.',eyebrow:'Feriados em diferentes países',heading:'Saiba se é feriado por lá antes de agendar',intro:'Um horário pode caber no expediente de todos e ainda cair no dia errado. Confira o calendário de feriados local de cada participante.',note:'O Common Hours sinaliza feriados em cada local sem ocultar o horário, deixando a decisão final para a equipe.'}
};

const guideExpansions = {
  converter:{
    en:[['Read the result in local terms','Start with the proposed time in one city, then read every other row as that participant will experience it. Check both the local date and the full start-to-end range. A meeting that begins during office hours may finish after them, and a late-evening meeting can cross into the following day. The working-hour shading is a guide, not a promise of availability.'],['Common conversion mistakes',['Using today’s UTC offset for a meeting months away.','Forgetting that a meeting can fall on different calendar dates across the International Date Line.','Checking only the start time instead of the entire duration.','Sending a plain time without its date, city or time zone.']],['Before you send the invitation','Move the proposed time earlier and later to compare the burden on each city. Check the holiday status for the actual meeting date, then copy or share the result so everyone sees the same cities, date, duration and local times. For recurring meetings, recheck dates near seasonal clock changes rather than assuming the offset stays fixed.']],
    es:[['Lee el resultado en horas locales','Empieza con la hora propuesta en una ciudad y revisa cada fila como la vivirá ese participante. Comprueba la fecha local y todo el intervalo. Una reunión puede empezar dentro del horario laboral y terminar fuera, o pasar al día siguiente. El sombreado laboral es una guía, no una promesa de disponibilidad.'],['Errores comunes de conversión',['Usar el desfase UTC de hoy para una reunión futura.','Olvidar que la reunión puede caer en fechas distintas.','Comprobar solo la hora de inicio y no la duración completa.','Enviar una hora sin fecha, ciudad ni zona horaria.']],['Antes de enviar la invitación','Mueve la hora para comparar el esfuerzo de cada ciudad, revisa los festivos de la fecha real y comparte el resultado para que todos vean las mismas ciudades, fecha, duración y horas locales. Revisa de nuevo las reuniones periódicas cerca de los cambios estacionales.']],
    fr:[['Lisez le résultat en heure locale','Partez de l’heure proposée dans une ville puis lisez chaque ligne comme le participant la vivra. Vérifiez la date locale et toute la durée. Une réunion peut commencer pendant les heures de travail et finir après, ou passer au lendemain. Les plages de travail restent une indication.'],['Erreurs fréquentes',['Utiliser le décalage UTC d’aujourd’hui pour une date future.','Oublier que la réunion peut tomber sur des dates différentes.','Vérifier seulement l’heure de début.','Envoyer une heure sans date, ville ni fuseau.']],['Avant d’envoyer l’invitation','Déplacez l’heure pour comparer l’effort demandé à chaque ville, vérifiez les jours fériés à la date réelle puis partagez le résultat. Pour une réunion récurrente, revérifiez les dates proches des changements saisonniers.']],
    de:[['Ergebnisse als Ortszeit lesen','Beginne mit der vorgeschlagenen Zeit in einer Stadt und lies jede weitere Zeile aus Sicht der dortigen Person. Prüfe Ortsdatum sowie Beginn und Ende. Ein Meeting kann während der Arbeitszeit beginnen und danach enden oder in den nächsten Tag reichen. Die Markierung der Arbeitszeit ist nur eine Orientierung.'],['Häufige Umrechnungsfehler',['Den heutigen UTC-Versatz für einen späteren Termin verwenden.','Unterschiedliche Kalendertage übersehen.','Nur den Beginn statt der gesamten Dauer prüfen.','Eine Uhrzeit ohne Datum, Stadt oder Zeitzone senden.']],['Vor dem Versand','Verschiebe die Zeit, vergleiche die Belastung für alle Städte und prüfe Feiertage am echten Datum. Teile anschließend das Ergebnis mit Städten, Datum, Dauer und Ortszeiten. Serientermine sollten rund um Zeitumstellungen erneut geprüft werden.']],
    pt:[['Leia o resultado em horário local','Comece pelo horário proposto em uma cidade e leia cada linha como o participante a verá. Confira a data local e todo o intervalo. Uma reunião pode começar durante o expediente e terminar depois, ou avançar para o dia seguinte. A faixa de trabalho é uma orientação, não uma confirmação de disponibilidade.'],['Erros comuns',['Usar o deslocamento UTC de hoje para uma data futura.','Esquecer que a reunião pode cair em datas diferentes.','Verificar apenas o início.','Enviar um horário sem data, cidade ou fuso.']],['Antes de enviar o convite','Mova o horário para comparar o impacto em cada cidade, confira os feriados da data real e compartilhe o resultado completo. Em reuniões recorrentes, revise novamente perto das mudanças sazonais de horário.']]
  },
  planner:{
    en:[['Balance convenience and fairness','For two nearby time zones, a normal working-hours overlap is usually straightforward. With three continents, there may be no painless answer. Treat the recommended time as a starting point: identify who is being asked to join early or late, ask whether that is acceptable, and rotate the inconvenience for recurring meetings. A fair pattern is often more sustainable than forcing the same clock time every week.'],['Check the day, not only the hour',['Confirm the local weekday for every city.','Review public-holiday notices before sending the invitation.','Watch for meetings that cross midnight in one location.','Allow for regional or company closures that a national calendar cannot know.']],['Create a clear meeting record','Share the Common Hours link with the invitation so participants can reopen the exact comparison. In the calendar description, include the meeting date, duration and a short list of local start times. Name the reference city only when useful; the local rows are what prevent confusion. If the meeting repeats, note who will absorb early or late hours next time.']],
    es:[['Equilibra comodidad y justicia','Con dos zonas cercanas suele existir una coincidencia laboral clara. Con tres continentes puede no haber una solución cómoda. Usa la recomendación como punto de partida, identifica quién debe conectarse temprano o tarde y alterna el esfuerzo en reuniones periódicas. Un patrón justo suele ser más sostenible que mantener siempre la misma hora.'],['Comprueba el día, no solo la hora',['Confirma el día local en cada ciudad.','Revisa los avisos de festivos antes de invitar.','Observa las reuniones que cruzan la medianoche.','Ten en cuenta cierres regionales o empresariales.']],['Crea un registro claro','Comparte el enlace de Common Hours para que todos reabran la misma comparación. Incluye fecha, duración y una lista breve de horas locales. Si la reunión se repite, indica quién asumirá la hora temprana o tardía la próxima vez.']],
    fr:[['Équilibrez confort et équité','Avec deux fuseaux proches, un chevauchement est souvent simple. Sur trois continents, aucune solution ne sera parfaite. Utilisez la recommandation comme point de départ, identifiez qui doit se connecter tôt ou tard et alternez cette contrainte pour les réunions récurrentes. Une rotation équitable est plus durable.'],['Vérifiez le jour, pas seulement l’heure',['Confirmez le jour local dans chaque ville.','Consultez les jours fériés avant d’inviter.','Repérez les réunions qui passent minuit.','Tenez compte des fermetures régionales ou d’entreprise.']],['Créez une référence claire','Partagez le lien Common Hours afin que tous rouvrent la même comparaison. Ajoutez la date, la durée et les heures locales à l’invitation. Pour une réunion récurrente, indiquez qui acceptera l’horaire tôt ou tard la prochaine fois.']],
    de:[['Komfort und Fairness ausgleichen','Bei zwei nahen Zeitzonen ist eine Überschneidung meist einfach. Über drei Kontinente gibt es oft keine schmerzfreie Lösung. Nutze die Empfehlung als Ausgangspunkt, erkenne frühe oder späte Belastungen und wechsle sie bei Serienterminen ab. Eine faire Rotation ist nachhaltiger als immer dieselbe Uhrzeit.'],['Nicht nur die Uhrzeit prüfen',['Bestätige den lokalen Wochentag jeder Stadt.','Prüfe Feiertagshinweise vor der Einladung.','Achte auf Meetings über Mitternacht.','Berücksichtige regionale oder betriebliche Schließungen.']],['Klare Meetingangaben erstellen','Teile den Common-Hours-Link, damit alle denselben Vergleich öffnen. Nenne Datum, Dauer und Ortszeiten in der Einladung. Bei Serienterminen sollte festgehalten werden, wer beim nächsten Mal die frühe oder späte Zeit übernimmt.']],
    pt:[['Equilibre conveniência e justiça','Com dois fusos próximos, a sobreposição costuma ser simples. Em três continentes talvez não exista uma opção indolor. Use a recomendação como ponto de partida, identifique quem participará cedo ou tarde e alterne esse esforço em reuniões recorrentes. Uma rotação justa é mais sustentável.'],['Confira o dia, não só a hora',['Confirme o dia local em cada cidade.','Veja os avisos de feriados antes de convidar.','Observe reuniões que atravessam a meia-noite.','Considere fechamentos regionais ou da empresa.']],['Crie um registro claro','Compartilhe o link do Common Hours para que todos reabram a mesma comparação. Inclua data, duração e horários locais no convite. Em reuniões recorrentes, registre quem assumirá o horário cedo ou tarde na próxima vez.']]
  },
  dst:{
    en:[['What the holiday check can tell you','The planner checks the meeting date in each selected location and displays a separate status for every city. A public-holiday warning does not automatically remove the suggested time: some teams work through a holiday, while regional observance and individual schedules vary. The warning gives the organizer a reason to confirm attendance before sending the invitation.'],['National, regional and company calendars',['National holidays are the most consistent cross-country signal.','Some holidays apply only to a state, province, territory or city.','Substitute days may move an observance when a holiday falls on a weekend.','Company shutdowns, school breaks and personal leave are outside a public calendar.']],['A practical holiday-aware workflow','Choose the actual date before judging the result. Read the status beside every location and investigate any warning with the local participant. If holiday information is unavailable, treat that as a prompt to confirm rather than as proof of a normal working day. For recurring meetings, inspect each occurrence separately because movable holidays and substitute days change from year to year.']],
    es:[['Qué indica la comprobación','El planificador revisa la fecha en cada ubicación y muestra un estado por ciudad. Un aviso de festivo no elimina automáticamente la hora: algunos equipos trabajan y la observancia regional varía. El aviso sirve para confirmar la asistencia antes de enviar la invitación.'],['Calendarios nacionales y regionales',['Los festivos nacionales son la señal más consistente.','Algunos festivos solo se aplican a una región o ciudad.','Los días sustitutos pueden mover la celebración.','Cierres empresariales y vacaciones personales no figuran en un calendario público.']],['Flujo práctico','Elige la fecha real, revisa cada ubicación y consulta cualquier aviso con el participante local. Si no hay datos, confirma en lugar de asumir que es un día laborable. En reuniones periódicas, revisa cada fecha porque los festivos móviles cambian cada año.']],
    fr:[['Ce que le contrôle indique','Le planificateur vérifie la date dans chaque lieu et affiche un statut par ville. Un avertissement ne supprime pas automatiquement l’heure proposée : certaines équipes travaillent et les pratiques régionales varient. Il invite l’organisateur à confirmer la présence.'],['Calendriers nationaux et régionaux',['Les jours fériés nationaux sont le signal le plus cohérent.','Certains ne concernent qu’une région ou une ville.','Un jour de remplacement peut déplacer l’observation.','Fermetures d’entreprise et congés personnels ne figurent pas dans un calendrier public.']],['Méthode pratique','Choisissez la date réelle, lisez chaque statut et confirmez tout avertissement avec la personne locale. Si les données manquent, demandez confirmation au lieu de supposer un jour ouvré. Vérifiez chaque occurrence d’une réunion récurrente.']],
    de:[['Was die Feiertagsprüfung zeigt','Der Planer prüft das Datum an jedem Ort und zeigt für jede Stadt einen eigenen Status. Eine Warnung entfernt die Zeit nicht automatisch: Manche Teams arbeiten, und regionale Regeln unterscheiden sich. Die Warnung ist ein Anlass, die Teilnahme vor der Einladung zu bestätigen.'],['Nationale und regionale Kalender',['Nationale Feiertage sind das verlässlichste Signal.','Manche gelten nur in einem Bundesland oder einer Stadt.','Ersatztage können die Beachtung verschieben.','Betriebsferien und persönliche Abwesenheiten fehlen in öffentlichen Kalendern.']],['Praktischer Ablauf','Wähle das echte Datum, lies jeden Status und kläre Warnungen mit der Person vor Ort. Fehlende Daten bedeuten, dass du nachfragen solltest, nicht dass sicher ein Arbeitstag ist. Prüfe bei Serienterminen jedes Datum einzeln.']],
    pt:[['O que a verificação informa','O planejador confere a data em cada local e mostra um status por cidade. Um aviso não remove automaticamente o horário: algumas equipes trabalham e a observância regional varia. O alerta ajuda o organizador a confirmar a presença antes do convite.'],['Calendários nacionais e regionais',['Feriados nacionais são o sinal mais consistente.','Alguns valem apenas para um estado ou cidade.','Dias substitutos podem mudar a observância.','Fechamentos da empresa e folgas pessoais não aparecem no calendário público.']],['Fluxo prático','Escolha a data real, leia cada status e confirme os avisos com o participante local. Se os dados estiverem indisponíveis, pergunte em vez de presumir um dia útil. Em reuniões recorrentes, revise cada data separadamente.']]
  }
};

const guideDeepening = {
  converter:{
    en:[['Example: New York, London and Mumbai','Suppose a one-hour call is proposed for 9:00 AM in New York. The converter shows the corresponding local time and date in London and Mumbai using the rules that apply on the selected date. Extend the duration to see whether anyone’s end time leaves normal working hours. Then move the meeting by 30 minutes and compare again. This is more reliable than memorizing offsets because the difference between New York and London changes temporarily when their daylight-saving dates do not match.'],['Why city names are better than abbreviations','Abbreviations such as CST, IST and BST can describe more than one time zone. A city plus a date is much less ambiguous because it identifies a named time zone and the seasonal rule in force. When sharing a proposal, include readable local times as well as the restoring link; recipients can understand the message immediately and reopen the full comparison if they want to test another time.']],
    es:[['Ejemplo con tres ciudades','Si propones una llamada de una hora a las 9:00 en Nueva York, el conversor muestra la fecha y hora correspondientes en Londres y Mumbai según las reglas de ese día. Amplía la duración y mueve la reunión en pasos de 30 minutos para comparar el impacto.'],['Por qué convienen las ciudades','Siglas como CST, IST y BST pueden significar zonas distintas. Una ciudad y una fecha identifican mejor la regla aplicable. Comparte horas locales legibles junto con el enlace para que todos puedan reabrir la comparación.']],
    fr:[['Exemple avec trois villes','Pour un appel d’une heure proposé à 9 h à New York, le convertisseur affiche la date et l’heure à Londres et Mumbai selon les règles du jour choisi. Modifiez la durée et déplacez l’heure par pas de 30 minutes pour comparer.'],['Pourquoi utiliser les villes','Des sigles comme CST, IST et BST peuvent désigner plusieurs fuseaux. Une ville et une date sont plus précises. Partagez les heures locales lisibles avec le lien permettant de rouvrir la comparaison.']],
    de:[['Beispiel mit drei Städten','Für einen einstündigen Anruf um 9 Uhr in New York zeigt der Umrechner Datum und Ortszeit in London und Mumbai nach den Regeln des gewählten Tages. Ändere Dauer und Startzeit in 30-Minuten-Schritten, um die Auswirkungen zu vergleichen.'],['Warum Städtenamen besser sind','Kürzel wie CST, IST und BST können mehrere Zeitzonen meinen. Stadt und Datum sind eindeutiger. Teile lesbare Ortszeiten zusammen mit dem Link zum vollständigen Vergleich.']],
    pt:[['Exemplo com três cidades','Para uma chamada de uma hora às 9h em Nova York, o conversor mostra a data e o horário em Londres e Mumbai segundo as regras do dia escolhido. Altere a duração e mova a reunião em passos de 30 minutos para comparar.'],['Por que usar cidades','Siglas como CST, IST e BST podem representar fusos diferentes. Cidade e data são mais precisas. Compartilhe horários locais legíveis junto com o link da comparação.']]
  },
  planner:{
    en:[['Example: a three-continent team','Imagine participants in Los Angeles, New York and London. A late morning meeting in New York may be early in California and late afternoon in Britain. Adding a colleague in Mumbai changes the trade-off completely. Start with the recommended compromise, examine whose time falls outside the green working-hours area, and test the previous or next day for holiday differences. If no option is comfortable, shorten the meeting, split topics into two sessions, or alternate the difficult time among regions.'],['Questions to confirm with participants',['Is the displayed public holiday observed by this person or organization?','Are the assumed 9-to-5 working hours appropriate for the team?','Does anyone need travel, school-run or prayer-time accommodation?','For a recurring series, how will early and late sessions be rotated?']]],
    es:[['Ejemplo de tres continentes','Con participantes en Los Ángeles, Nueva York y Londres, una mañana en Nueva York puede ser muy temprano en California y tarde en Gran Bretaña. Añadir Mumbai cambia por completo el equilibrio. Prueba días cercanos, acorta la reunión o alterna la hora difícil.'],['Preguntas para el equipo',['¿Se observa realmente el festivo mostrado?','¿El horario de 9 a 5 refleja al equipo?','¿Hay necesidades personales que considerar?','¿Cómo se alternarán las horas tempranas y tardías?']]],
    fr:[['Exemple sur trois continents','Avec Los Angeles, New York et Londres, une fin de matinée à New York peut être très tôt en Californie et tard en Grande-Bretagne. Ajouter Mumbai change tout l’équilibre. Essayez les jours voisins, raccourcissez la réunion ou alternez l’horaire difficile.'],['Questions à confirmer',['Le jour férié est-il observé par cette organisation ?','Les heures de 9 à 17 h conviennent-elles ?','Existe-t-il des contraintes personnelles ?','Comment alterner les horaires tôt et tard ?']]],
    de:[['Beispiel über drei Kontinente','Bei Los Angeles, New York und London kann der späte Vormittag in New York in Kalifornien sehr früh und in Großbritannien spät sein. Mumbai verändert den Kompromiss vollständig. Prüfe Nachbartage, verkürze das Meeting oder wechsle die schwierige Zeit ab.'],['Fragen an das Team',['Wird der angezeigte Feiertag tatsächlich beachtet?','Passen Arbeitszeiten von 9 bis 17 Uhr?','Gibt es persönliche Einschränkungen?','Wie werden frühe und späte Termine rotiert?']]],
    pt:[['Exemplo em três continentes','Com Los Angeles, Nova York e Londres, o fim da manhã em Nova York pode ser muito cedo na Califórnia e tarde na Grã-Bretanha. Adicionar Mumbai muda todo o equilíbrio. Teste dias próximos, reduza a reunião ou alterne o horário difícil.'],['Perguntas para a equipe',['O feriado exibido é realmente observado?','O expediente de 9h às 17h serve para a equipe?','Há restrições pessoais?','Como os horários cedo e tarde serão alternados?']]]
  },
  dst:{
    en:[['India and other complex holiday calendars','Some countries combine nationwide holidays with state, religious, bank and substitute observances. India is a good example: Republic Day, Independence Day and Gandhi Jayanti are fixed nationwide dates, while many other important observances vary by year or location. Common Hours includes a built-in check for those three nationwide Indian holidays when the external calendar cannot supply India data. For every other unavailable date, the site says so rather than incorrectly calling it a working day.'],['How to handle a warning','A warning should begin a conversation, not make the decision by itself. Ask the participant whether the holiday applies to their location and employer, whether they expect to be working, and whether a substitute day is observed. If attendance is optional, state that clearly. If the meeting is important or customer-facing, move it when possible. Record the decision in the invitation so the same question does not reappear later.']],
    es:[['India y calendarios complejos','Algunos países combinan festivos nacionales, estatales, religiosos y sustitutos. Common Hours incorpora los tres festivos nacionales fijos de India: Día de la República, Día de la Independencia y Gandhi Jayanti. Si faltan datos para otra fecha, lo indica en lugar de llamarla laborable.'],['Cómo tratar un aviso','Un aviso inicia una conversación. Confirma si el festivo se aplica al lugar y empresa, si se trabaja y si existe un día sustituto. Para una reunión importante, cambia la fecha cuando sea posible y registra la decisión en la invitación.']],
    fr:[['L’Inde et les calendriers complexes','Certains pays combinent jours fériés nationaux, régionaux, religieux et de remplacement. Common Hours intègre les trois dates nationales fixes en Inde : Republic Day, Independence Day et Gandhi Jayanti. Si une autre date manque, le site le signale au lieu de l’appeler jour ouvré.'],['Réagir à un avertissement','Un avertissement ouvre une discussion. Confirmez son application au lieu et à l’employeur, le travail prévu et un éventuel jour de remplacement. Déplacez une réunion importante si possible et notez la décision dans l’invitation.']],
    de:[['Indien und komplexe Kalender','Manche Länder kombinieren nationale, regionale, religiöse und Ersatzfeiertage. Common Hours prüft Indiens drei feste nationale Daten: Republic Day, Independence Day und Gandhi Jayanti. Fehlen Daten für einen anderen Tag, wird das angezeigt statt fälschlich Arbeitstag zu melden.'],['Mit Warnungen umgehen','Eine Warnung beginnt das Gespräch. Kläre, ob sie für Ort und Arbeitgeber gilt, ob gearbeitet wird und ob es einen Ersatztag gibt. Verschiebe wichtige Meetings wenn möglich und dokumentiere die Entscheidung in der Einladung.']],
    pt:[['Índia e calendários complexos','Alguns países combinam feriados nacionais, estaduais, religiosos e substitutos. O Common Hours inclui as três datas nacionais fixas da Índia: Republic Day, Independence Day e Gandhi Jayanti. Se faltarem dados em outra data, o site informa em vez de chamá-la de dia útil.'],['Como agir diante do aviso','O aviso inicia uma conversa. Confirme se o feriado vale para o local e empregador, se haverá trabalho e se existe dia substituto. Mude reuniões importantes quando possível e registre a decisão no convite.']]
  }
};

const guideLinks = {
  converter:'meeting-time-zone-converter.html',
  planner:'international-meeting-planner.html',
  dst:'daylight-saving-holidays.html'
};

function renderGuide(language){
  const lang=guideUi[language]?language:'en';
  const key=document.body.dataset.guide;
  const base={...guides[key][lang],...(key==='dst'?holidayGuidePositioning[lang]:{})};
  const data={...base,sections:[...base.sections,...(guideExpansions[key]?.[lang]||[]),...(guideDeepening[key]?.[lang]||[])]};
  const ui=guideUi[lang];
  document.documentElement.lang=lang;
  document.title=data.title;
  document.querySelector('meta[name="description"]').content=data.description;
  document.getElementById('language').value=lang;
  document.getElementById('guide-content').innerHTML=`
    <p class="eyebrow">${data.eyebrow}</p>
    <h1>${data.heading}</h1>
    <p class="lede">${data.intro}</p>
    <a class="primary-button" href="./">${ui.planner}</a>
    ${data.sections.map(([heading,content])=>`<section><h2>${heading}</h2>${Array.isArray(content)?`<ul class="guide-points">${content.map(item=>`<li>${item}</li>`).join('')}</ul>`:`<p>${content}</p>`}</section>`).join('')}
    <aside class="guide-note"><p>${data.note}</p></aside>
    <nav class="guide-nav" aria-label="${ui.more}"><h2>${ui.more}</h2><ul>${Object.entries(guideLinks).filter(([id])=>id!==key).map(([id,url])=>`<li><a href="${url}">${guides[id][lang].heading}</a></li>`).join('')}</ul></nav>`;
  document.querySelectorAll('[data-ui="language"]').forEach(el=>el.textContent=ui.language);
  document.querySelectorAll('[data-ui="home"]').forEach(el=>el.textContent=ui.home);
  document.querySelectorAll('[data-ui="privacy"]').forEach(el=>el.textContent=ui.privacy);
  document.querySelectorAll('[data-ui="footer"]').forEach(el=>el.textContent=ui.footer);
  localStorage.setItem('commonHoursLanguage',lang);
}

const browserLanguage=(navigator.language||'en').slice(0,2);
const initialLanguage=localStorage.getItem('commonHoursLanguage') || (guideUi[browserLanguage]?browserLanguage:'en');
document.getElementById('language').addEventListener('change',event=>renderGuide(event.target.value));
document.getElementById('theme-toggle').addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;localStorage.setItem('commonHoursTheme',theme);});
document.documentElement.dataset.theme=localStorage.getItem('commonHoursTheme') || (matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
renderGuide(initialLanguage);
