const guideUi = {
  en:{language:'Language',planner:'Open the free meeting planner',more:'More useful guides',home:'Meeting planner',privacy:'Privacy',footer:'A free world meeting time finder.'},
  es:{language:'Idioma',planner:'Abrir el planificador gratuito',more:'Más guías útiles',home:'Planificador de reuniones',privacy:'Privacidad',footer:'Un buscador gratuito de horarios mundiales.'},
  fr:{language:'Langue',planner:'Ouvrir le planificateur gratuit',more:'Autres guides utiles',home:'Planificateur de réunion',privacy:'Confidentialité',footer:'Un outil gratuit de recherche d’horaires mondiaux.'},
  de:{language:'Sprache',planner:'Kostenlosen Meetingplaner öffnen',more:'Weitere hilfreiche Leitfäden',home:'Meetingplaner',privacy:'Datenschutz',footer:'Ein kostenloser weltweiter Meetingzeit-Finder.'},
  pt:{language:'Idioma',planner:'Abrir o planejador gratuito',more:'Mais guias úteis',home:'Planejador de reuniões',privacy:'Privacidade',footer:'Um localizador gratuito de horários mundiais.'}
};

const guides = {
  converter:{
    en:{title:'Meeting Time-Zone Converter | Common Hours',description:'Convert meeting times across cities and time zones while comparing working hours, dates, weekends and holidays.',eyebrow:'Time-zone conversion',heading:'Convert a meeting time for everyone',intro:'A useful meeting time-zone converter does more than add or subtract hours. It should use the meeting date, each city’s local rules and the length of the meeting.',sections:[['Why the date matters','Time-zone differences are not fixed throughout the year. Countries change clocks on different dates, and many never change them. Always convert the actual meeting date rather than relying on a familiar offset.'],['How to convert a proposed meeting',['Add every participant’s city, not only a UTC offset.','Choose the intended meeting date and duration.','Compare the local start and end times for everyone.','Move the selected time in 30-minute steps until the trade-off feels reasonable.']]],note:'Common Hours uses named city time zones for the selected date, helping account for applicable daylight-saving changes automatically.'},
    es:{title:'Conversor de zonas horarias para reuniones | Common Hours',description:'Convierte horas de reunión entre ciudades y compara horarios laborales, fechas, fines de semana y festivos.',eyebrow:'Conversión de zonas horarias',heading:'Convierte una hora de reunión para todos',intro:'Un buen conversor hace más que sumar o restar horas. Debe considerar la fecha, las reglas locales de cada ciudad y la duración.',sections:[['Por qué importa la fecha','Las diferencias horarias no son fijas todo el año. Los países cambian el reloj en fechas distintas y muchos nunca lo cambian. Convierte siempre la fecha real de la reunión.'],['Cómo convertir una propuesta',['Añade la ciudad de cada participante, no solo un desfase UTC.','Elige la fecha y duración previstas.','Compara las horas locales de inicio y fin.','Mueve la hora en intervalos de 30 minutos hasta encontrar un equilibrio razonable.']]],note:'Common Hours usa zonas horarias de ciudades para la fecha elegida y contempla automáticamente los cambios de horario aplicables.'},
    fr:{title:'Convertisseur de fuseaux horaires pour réunions | Common Hours',description:'Convertissez les heures de réunion entre villes et comparez horaires de travail, dates, week-ends et jours fériés.',eyebrow:'Conversion de fuseaux horaires',heading:'Convertissez une heure de réunion pour tous',intro:'Un bon convertisseur ne se contente pas d’ajouter ou soustraire des heures. Il tient compte de la date, des règles locales et de la durée.',sections:[['Pourquoi la date compte','Les écarts horaires ne restent pas fixes toute l’année. Les pays changent d’heure à des dates différentes et beaucoup ne changent jamais. Convertissez toujours la date réelle.'],['Comment convertir une proposition',['Ajoutez la ville de chaque participant, pas seulement un décalage UTC.','Choisissez la date et la durée prévues.','Comparez les heures locales de début et de fin.','Déplacez l’heure par pas de 30 minutes jusqu’à obtenir un compromis raisonnable.']]],note:'Common Hours utilise les fuseaux des villes à la date choisie afin de tenir automatiquement compte des changements d’heure applicables.'},
    de:{title:'Zeitzonen-Umrechner für Meetings | Common Hours',description:'Rechne Meetingzeiten zwischen Städten um und vergleiche Arbeitszeiten, Daten, Wochenenden und Feiertage.',eyebrow:'Zeitzonenumrechnung',heading:'Rechne eine Meetingzeit für alle um',intro:'Ein guter Zeitzonen-Umrechner addiert oder subtrahiert nicht nur Stunden. Er berücksichtigt Datum, lokale Regeln und Meetingdauer.',sections:[['Warum das Datum wichtig ist','Zeitunterschiede bleiben nicht das ganze Jahr gleich. Länder stellen ihre Uhren an unterschiedlichen Tagen um, viele gar nicht. Rechne deshalb immer das tatsächliche Meetingdatum um.'],['So rechnest du einen Vorschlag um',['Füge die Stadt jeder Person hinzu, nicht nur einen UTC-Versatz.','Wähle Datum und Dauer des Meetings.','Vergleiche lokale Start- und Endzeiten.','Verschiebe die Zeit in 30-Minuten-Schritten, bis der Kompromiss passt.']]],note:'Common Hours verwendet benannte Stadtzeitzonen für das gewählte Datum und berücksichtigt damit geltende Zeitumstellungen automatisch.'},
    pt:{title:'Conversor de fusos horários para reuniões | Common Hours',description:'Converta horários entre cidades e compare expediente, datas, fins de semana e feriados.',eyebrow:'Conversão de fusos horários',heading:'Converta um horário de reunião para todos',intro:'Um bom conversor faz mais do que somar ou subtrair horas. Ele considera a data, as regras locais de cada cidade e a duração.',sections:[['Por que a data importa','As diferenças de horário não são fixas durante o ano. Países mudam os relógios em datas diferentes e muitos nunca mudam. Converta sempre a data real da reunião.'],['Como converter uma proposta',['Adicione a cidade de cada participante, não apenas um deslocamento UTC.','Escolha a data e a duração previstas.','Compare os horários locais de início e término.','Mova o horário em passos de 30 minutos até chegar a um equilíbrio razoável.']]],note:'O Common Hours usa fusos de cidades para a data escolhida, considerando automaticamente as mudanças de horário aplicáveis.'}
  },
  planner:{
    en:{title:'International Meeting Planner Guide | Common Hours',description:'Plan fair international meetings across countries with a practical checklist for time zones, working hours and meeting duration.',eyebrow:'International scheduling',heading:'Plan a fair international meeting',intro:'The best international meeting time is not always perfect for everyone. A clear process helps you find the least disruptive option and share the inconvenience fairly.',sections:[['A practical planning checklist',['List every participant’s city and confirm the meeting date.','Set the real duration before comparing availability.','Prefer overlap within normal weekday working hours.','Check local weekends and public-holiday notices.','If no good overlap exists, rotate early or late meetings over time.']],['Make the invitation unambiguous','Write the date, local time and time zone in the invitation. A calendar invitation is helpful, but a readable summary lets participants catch mistakes before the meeting.']],note:'For recurring global meetings, fairness often matters more than choosing the same clock time every week.'},
    es:{title:'Guía para planificar reuniones internacionales | Common Hours',description:'Planifica reuniones internacionales justas con una lista práctica sobre zonas horarias, horarios laborales y duración.',eyebrow:'Planificación internacional',heading:'Planifica una reunión internacional justa',intro:'La mejor hora internacional no siempre es perfecta para todos. Un proceso claro ayuda a encontrar la opción menos incómoda y repartir el esfuerzo.',sections:[['Lista práctica',['Anota la ciudad de cada participante y confirma la fecha.','Define la duración real antes de comparar disponibilidad.','Prefiere coincidencias dentro del horario laboral normal.','Comprueba fines de semana y avisos de festivos.','Si no hay una buena coincidencia, alterna las reuniones tempranas o tardías.']],['Haz que la invitación sea inequívoca','Escribe la fecha, hora local y zona horaria en la invitación. El calendario ayuda, pero un resumen legible permite detectar errores.']],note:'En reuniones globales periódicas, la equidad suele importar más que mantener siempre la misma hora de reloj.'},
    fr:{title:'Guide de planification de réunion internationale | Common Hours',description:'Planifiez des réunions internationales équitables grâce à une liste pratique sur les fuseaux, horaires et durées.',eyebrow:'Planification internationale',heading:'Planifiez une réunion internationale équitable',intro:'La meilleure heure n’est pas toujours parfaite pour tous. Une méthode claire aide à trouver l’option la moins gênante et à partager l’effort.',sections:[['Liste pratique',['Indiquez la ville de chaque participant et confirmez la date.','Fixez la durée réelle avant de comparer les disponibilités.','Privilégiez les heures de travail normales en semaine.','Vérifiez les week-ends et avis de jours fériés.','Sans bon chevauchement, alternez les réunions tôt ou tard.']],['Rendez l’invitation sans ambiguïté','Écrivez la date, l’heure locale et le fuseau dans l’invitation. Le calendrier aide, mais un résumé lisible permet de repérer les erreurs.']],note:'Pour les réunions mondiales récurrentes, l’équité compte souvent davantage que le maintien de la même heure chaque semaine.'},
    de:{title:'Leitfaden für internationale Meetings | Common Hours',description:'Plane faire internationale Meetings mit einer praktischen Checkliste zu Zeitzonen, Arbeitszeiten und Dauer.',eyebrow:'Internationale Planung',heading:'Plane ein faires internationales Meeting',intro:'Die beste internationale Meetingzeit ist nicht immer für alle perfekt. Ein klarer Ablauf hilft, die geringste Belastung zu finden und fair zu verteilen.',sections:[['Praktische Checkliste',['Notiere die Stadt aller Teilnehmenden und bestätige das Datum.','Lege die echte Dauer vor dem Vergleich fest.','Bevorzuge Überschneidungen innerhalb normaler Arbeitszeiten.','Prüfe lokale Wochenenden und Feiertagshinweise.','Wenn es keine gute Überschneidung gibt, wechsle frühe und späte Termine ab.']],['Formuliere die Einladung eindeutig','Nenne Datum, Ortszeit und Zeitzone. Eine Kalendereinladung hilft, aber eine lesbare Zusammenfassung macht Fehler sichtbar.']],note:'Bei wiederkehrenden globalen Meetings ist Fairness oft wichtiger als jede Woche dieselbe Uhrzeit.'},
    pt:{title:'Guia para planejar reuniões internacionais | Common Hours',description:'Planeje reuniões internacionais justas com uma lista prática de fusos, expedientes e duração.',eyebrow:'Agendamento internacional',heading:'Planeje uma reunião internacional justa',intro:'O melhor horário internacional nem sempre é perfeito para todos. Um processo claro ajuda a encontrar a opção menos inconveniente e dividir o esforço.',sections:[['Lista prática',['Registre a cidade de cada participante e confirme a data.','Defina a duração real antes de comparar disponibilidade.','Prefira sobreposição dentro do expediente normal.','Confira fins de semana e avisos de feriados locais.','Sem boa sobreposição, alterne reuniões cedo ou tarde.']],['Deixe o convite inequívoco','Informe a data, o horário local e o fuso no convite. O calendário ajuda, mas um resumo legível permite detectar erros.']],note:'Para reuniões globais recorrentes, a justiça costuma ser mais importante do que manter sempre o mesmo horário.'}
  },
  dst:{
    en:{title:'Daylight Saving Time and Holiday Meeting Guide | Common Hours',description:'Avoid international scheduling errors caused by daylight-saving changes, date boundaries, weekends and public holidays.',eyebrow:'Dates and local calendars',heading:'Avoid daylight-saving and holiday surprises',intro:'International schedules can shift even when nobody changes the meeting. Clock changes, date boundaries and public holidays must be checked against the actual meeting date.',sections:[['Daylight-saving changes are not synchronized','Regions begin and end daylight saving time on different dates. For several weeks each year, a familiar city-to-city difference may be one hour larger or smaller than expected. Some places do not observe daylight saving time at all.'],['Check the local calendar',['Confirm the date shown in every participant’s city.','Look for weekend differences when meetings cross midnight.','Treat holiday notices as warnings rather than automatic exclusions.','Recheck recurring meetings near seasonal clock changes.']]],note:'Common Hours flags public holidays instead of hiding possible times, leaving the final decision with the people attending.'},
    es:{title:'Guía de horario de verano y festivos | Common Hours',description:'Evita errores causados por cambios de horario, límites de fecha, fines de semana y festivos.',eyebrow:'Fechas y calendarios locales',heading:'Evita sorpresas de horario de verano y festivos',intro:'Los horarios internacionales pueden cambiar aunque nadie mueva la reunión. Hay que comprobar los cambios de reloj, fechas y festivos para el día real.',sections:[['Los cambios no están sincronizados','Las regiones comienzan y terminan el horario de verano en fechas distintas. Durante varias semanas, la diferencia habitual entre ciudades puede variar una hora. Algunos lugares nunca cambian el reloj.'],['Comprueba el calendario local',['Confirma la fecha mostrada en cada ciudad.','Busca diferencias de fin de semana cuando se cruza la medianoche.','Trata los avisos de festivos como advertencias, no exclusiones automáticas.','Revisa las reuniones periódicas cerca de los cambios estacionales.']]],note:'Common Hours señala los festivos sin ocultar horas posibles, dejando la decisión final a los participantes.'},
    fr:{title:'Guide heure d’été et jours fériés | Common Hours',description:'Évitez les erreurs dues aux changements d’heure, changements de date, week-ends et jours fériés.',eyebrow:'Dates et calendriers locaux',heading:'Évitez les surprises liées aux changements d’heure et jours fériés',intro:'Les horaires internationaux peuvent changer sans déplacer la réunion. Vérifiez les changements d’heure, de date et les jours fériés pour la date réelle.',sections:[['Les changements ne sont pas synchronisés','Les régions commencent et terminent l’heure d’été à des dates différentes. Pendant plusieurs semaines, l’écart habituel entre deux villes peut varier d’une heure. Certains lieux ne changent jamais d’heure.'],['Vérifiez le calendrier local',['Confirmez la date affichée dans chaque ville.','Repérez les différences de week-end lors du passage à minuit.','Considérez les avis de jours fériés comme des avertissements.','Revérifiez les réunions récurrentes près des changements saisonniers.']]],note:'Common Hours signale les jours fériés sans masquer les heures possibles, laissant la décision finale aux participants.'},
    de:{title:'Leitfaden zu Sommerzeit und Feiertagen | Common Hours',description:'Vermeide internationale Planungsfehler durch Zeitumstellungen, Datumsgrenzen, Wochenenden und Feiertage.',eyebrow:'Daten und lokale Kalender',heading:'Vermeide Überraschungen durch Sommerzeit und Feiertage',intro:'Internationale Zeiten können sich ändern, obwohl niemand das Meeting verschiebt. Zeitumstellungen, Datumsgrenzen und Feiertage müssen für das echte Datum geprüft werden.',sections:[['Zeitumstellungen sind nicht synchron','Regionen beginnen und beenden die Sommerzeit an verschiedenen Tagen. Mehrere Wochen im Jahr kann der gewohnte Unterschied zwischen Städten um eine Stunde abweichen. Manche Orte stellen nie um.'],['Prüfe den lokalen Kalender',['Bestätige das Datum in jeder Stadt.','Achte beim Überschreiten von Mitternacht auf Wochenenden.','Behandle Feiertagshinweise als Warnungen, nicht als automatische Ausschlüsse.','Prüfe Serientermine rund um saisonale Zeitumstellungen erneut.']]],note:'Common Hours kennzeichnet Feiertage, ohne mögliche Zeiten auszublenden. Die endgültige Entscheidung bleibt bei den Teilnehmenden.'},
    pt:{title:'Guia de horário de verão e feriados | Common Hours',description:'Evite erros de agendamento causados por mudanças de horário, datas, fins de semana e feriados.',eyebrow:'Datas e calendários locais',heading:'Evite surpresas com horário de verão e feriados',intro:'Horários internacionais podem mudar mesmo sem alterar a reunião. Mudanças de relógio, viradas de data e feriados devem ser conferidos para a data real.',sections:[['As mudanças não são sincronizadas','Regiões iniciam e terminam o horário de verão em datas diferentes. Durante semanas, a diferença habitual entre cidades pode variar uma hora. Alguns lugares nunca mudam o relógio.'],['Confira o calendário local',['Confirme a data exibida em cada cidade.','Observe fins de semana quando a reunião cruza a meia-noite.','Trate avisos de feriado como alertas, não exclusões automáticas.','Revise reuniões recorrentes perto das mudanças sazonais.']]],note:'O Common Hours sinaliza feriados sem ocultar horários possíveis, deixando a decisão final para os participantes.'}
  }
};

const guideLinks = {
  converter:'meeting-time-zone-converter.html',
  planner:'international-meeting-planner.html',
  dst:'daylight-saving-holidays.html'
};

function renderGuide(language){
  const lang=guideUi[language]?language:'en';
  const key=document.body.dataset.guide;
  const data=guides[key][lang];
  const ui=guideUi[lang];
  document.documentElement.lang=lang;
  document.title=data.title;
  document.querySelector('meta[name="description"]').content=data.description;
  document.getElementById('language').value=lang;
  document.getElementById('guide-content').innerHTML=`
    <p class="eyebrow">${data.eyebrow}</p>
    <h1>${data.heading}</h1>
    <p class="lede">${data.intro}</p>
    <a class="primary-button" href="./">${ui.planner}</a>
    ${data.sections.map(([heading,content])=>`<section><h2>${heading}</h2>${Array.isArray(content)?`<ul class="guide-points">${content.map(item=>`<li>${item}</li>`).join('')}</ul>`:`<p>${content}</p>`}</section>`).join('')}
    <aside class="guide-note"><p>${data.note}</p></aside>
    <nav class="guide-nav" aria-label="${ui.more}"><h2>${ui.more}</h2><ul>${Object.entries(guideLinks).filter(([id])=>id!==key).map(([id,url])=>`<li><a href="${url}">${guides[id][lang].heading}</a></li>`).join('')}</ul></nav>`;
  document.querySelectorAll('[data-ui="language"]').forEach(el=>el.textContent=ui.language);
  document.querySelectorAll('[data-ui="home"]').forEach(el=>el.textContent=ui.home);
  document.querySelectorAll('[data-ui="privacy"]').forEach(el=>el.textContent=ui.privacy);
  document.querySelectorAll('[data-ui="footer"]').forEach(el=>el.textContent=ui.footer);
  localStorage.setItem('commonHoursLanguage',lang);
}

const browserLanguage=(navigator.language||'en').slice(0,2);
const initialLanguage=localStorage.getItem('commonHoursLanguage') || (guideUi[browserLanguage]?browserLanguage:'en');
document.getElementById('language').addEventListener('change',event=>renderGuide(event.target.value));
document.getElementById('theme-toggle').addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;localStorage.setItem('commonHoursTheme',theme);});
document.documentElement.dataset.theme=localStorage.getItem('commonHoursTheme') || (matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
renderGuide(initialLanguage);
