"""Patch the per-country weekend map into app.js.

The planner assumed Saturday+Sunday everywhere. That is wrong for 28 countries
-- Saudi Arabia, Qatar, Israel, Egypt, Kuwait, Bahrain, Oman and most of the
Gulf keep Friday+Saturday; Hong Kong, Niger and a few others rest on Sunday
only; Brunei takes Friday and Sunday; Iran takes Friday alone. For those
visitors the planner showed Friday as a working day and Sunday as a weekend,
exactly inverted, on the one question the site exists to get right.

The data is per country and per year, so it tracks real changes: the library
correctly has the UAE on Sat+Sun following its 2022 move, while its neighbours
stay Fri+Sat.

Only the exceptions are emitted; everything else falls back to Sat+Sun, so the
block stays a few hundred bytes. Run it annually with the place data, or
whenever a country is reported to have moved its weekend.

Usage:  python tools/gen_weekends.py
Requires: pip install holidays  (pin must match the workflows)
"""
import os, re, sys
from datetime import date

try:
    import holidays
except ImportError:
    sys.exit("pip install holidays  (python-holidays) first")

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
APP = os.path.join(REPO, "app.js")
START = "// --- WEEKENDS:START (generated by tools/gen_weekends.py) ---"
END = "// --- WEEKENDS:END ---"
DAY = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
DEFAULT = (5, 6)
YEAR = date.today().year

exceptions = {}
for key, val in holidays.registry.COUNTRIES.items():
    code = val[1]
    try:
        h = holidays.country_holidays(code, years=YEAR)
        wk = tuple(sorted(getattr(h, "weekend", ()) or ()))
    except Exception:
        continue
    if wk and wk != DEFAULT:
        exceptions[code] = wk

pairs = ",".join(
    "%s:[%s]" % (c, ",".join("'%s'" % DAY[d] for d in wk))
    for c, wk in sorted(exceptions.items()))

block = (
    START + "\n"
    "// Countries whose weekend is NOT Saturday+Sunday, from python-holidays for\n"
    f"// {YEAR}. Everything absent from this map uses the Sat+Sun default. Weekday\n"
    "// names match the short-form strings localParts() produces.\n"
    "const WEEKEND_DEFAULT=['Sat','Sun'];\n"
    f"const WEEKEND_BY_CC={{{pairs}}};\n"
    "function weekendDays(cc){ return (cc && WEEKEND_BY_CC[cc]) || WEEKEND_DEFAULT; }\n"
    "function isWeekendDay(weekdayName, cc){ return weekendDays(cc).indexOf(weekdayName)!==-1; }\n"
    + END)

s = open(APP, encoding="utf-8").read()
if START in s:
    s = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, s, flags=re.S)
else:
    anchor = "const state = {"
    assert s.count(anchor) == 1, "could not find the insertion anchor in app.js"
    s = s.replace(anchor, block + "\n\n" + anchor)
open(APP, "w", encoding="utf-8").write(s)

print(f"  {len(exceptions)} countries with a non Sat+Sun weekend, {len(block)} bytes")
for c, wk in sorted(exceptions.items()):
    print(f"     {c}  {'+'.join(DAY[d] for d in wk)}")
